version: "3"
services:
  db:
    image: postgres:11
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=homepage-user
      - POSTGRES_PASSWORD=homepage-password
      - POSTGRES_DB=homepage