api:
  max-page-count:
    article: 4

#spring.profiles.active=test
hibernate:
  jdbc:
    time_zone: UTC


spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    show-sql: true

graphql:
  servlet:
    exception-handlers-enabled: true
    cors-enabled: true
    cors:
      allowed-headers:
        - "Origin"
        - "Content-Type"
        - "X-Auth-Token"
      allowed-origins:
        - "http://127.0.0.1:3000"
      allowed-methods:
        - "POST"
